import { Inter } from "next/font/google";
import "./globals.css";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


import { Web3Provider } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <Web3Provider>
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
